- hosts: all
  become: true
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    service:
      name: nginx
      state: started
  - name: Add nginx conf
    templates:
      src: "{{ path_to_nginx_conf }}"
      dest: /etc/nginx/nginx.conf
    notify: Restart nginx
    
  handlers:                            
  - name: "Restart nginx"              
    service:                           
      name: "nginx"                    
      state: "restarted" 