- hosts: all
  become: true
  vars:                                                               
    app_repo: https://gitlab.com/qacdevops/flask-stages.git 
  tasks:
  - name: Clone a Git repo
    git:
      repo: "{{app_repo}}"
      dest: home/ubuntu/cristiana/app_repo
      clone: yes
      update: yes

  - name: Creating a file containing the hosts IP 
    template:                          
      src: "{{ ansible_default_ipv4.address }}"  
      dest: /home/ubuntu/hots_ip.txt
    notify: storing hosts IP address

  handlers:                            
  - name: "Print message if the system is Ubuntu"              
    debug:
      msg: "Your OS is {{ ansible_distribution }}"
    when: "{{ ansible_distribution }}== ubuntu"