- hosts: all
  become: true
  vars:                                                               
    app_repo: https://gitlab.com/qacdevops/flask-stages.git
    host_ip: "{{ansible_default_ipv4.address}}"
  tasks:
  - name: Clone a Git repo
    git:
      repo: "{{app_repo}}"
      dest: home/ubuntu/cristiana/app_repo
      clone: yes
      update: yes

  - name: Creating a file containing the hosts IP 
    template:                          
      src: "{{ host_ip }}"  
      dest: /home/ubuntu/hot_ip.txt
    

  handlers:                            
  - name: "Print message if the system is Ubuntu"              
    debug:
      msg: "Your OS is {{ ansible_distribution }}"
    when: ansible_distribution == "Ubuntu"